"use client";

import { useState, useRef } from "react";
import {
  ArrowRight,
  Check,
  Sparkles,
  FileText,
  Users,
  Zap,
  ChevronDown,
  ChevronUp,
  Star,
  Rocket,
  Brain,
  Share2,
  UserCircle,
} from "lucide-react";

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState(null);

  const tryItRef = useRef(null);
  const howItWorksRef = useRef(null);
  const useCasesRef = useRef(null);
  const pricingRef = useRef(null);
  const faqRef = useRef(null);

  const scrollToSection = (ref) => {
    ref.current.scrollIntoView({ behavior: "smooth" });
  };

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const faqItems = [
    {
      question: "How does Brifify generate project briefs?",
      answer:
        "Brifify uses advanced AI to analyze your inputs and generate comprehensive project briefs. Simply provide basic information about your project, and our AI will create a detailed brief with all necessary sections and considerations.",
    },
    {
      question: "Can I customize the generated briefs?",
      answer:
        "All briefs generated by Brifify are fully customizable. You can edit, add, or remove sections as needed to match your specific project requirements.",
    },
    {
      question: "Is my data secure with Brifify?",
      answer:
        "Yes, we take data security very seriously. All your project information is encrypted and stored securely. We never share your data with third parties without your explicit permission.",
    },
    {
      question: "Can I export my briefs to other formats?",
      answer:
        "Yes, Brifify allows you to export your briefs in multiple formats including PDF, Word, and HTML to easily share with your team or clients.",
    },
    {
      question: "Do you offer team collaboration features?",
      answer:
        "Yes, our Professional and Enterprise plans include team collaboration features that allow multiple team members to work on the same brief, add comments, and track changes.",
    },
  ];

  const pricingPlans = [
    {
      name: "Free",
      price: "$0",
      period: "forever",
      description: "Perfect for individuals just getting started",
      features: [
        "5 briefs per month",
        "Basic templates",
        "Export to PDF",
        "Email support",
      ],
      cta: "Get Started",
      popular: false,
    },
    {
      name: "Professional",
      price: "$19",
      period: "per month",
      description: "Ideal for professionals and small teams",
      features: [
        "Unlimited briefs",
        "All templates",
        "Export to multiple formats",
        "Team collaboration",
        "Priority support",
      ],
      cta: "Start Free Trial",
      popular: true,
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "pricing",
      description: "For organizations with advanced needs",
      features: [
        "Everything in Professional",
        "Custom templates",
        "API access",
        "SSO authentication",
        "Dedicated account manager",
      ],
      cta: "Contact Sales",
      popular: false,
    },
  ];

  return (
    <div className="w-full mx-auto font-inter bg-gradient-to-br from-white to-gray-50 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMiIgY3k9IjIiIHI9IjEiIGZpbGw9IiNlMmUyZTIiLz48L3N2Zz4=')]">
      {/* Hero Section - Gradient background */}
      <div className="max-w-6xl mx-auto px-4 md:px-8">
        <section className="py-16 max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 gap-8 items-center mb-32">
            <div className="text-left">
              <h1 className="text-3xl md:text-4xl lg:text-4xl font-bold font-poppins mb-6 leading-snug">
                <span className="text-gray-800">Create Technical Briefs</span>{" "}
                <br />
                <span className="bg-clip-text text-transparent bg-[#ff00ac]">
                  That Developers Understand
                </span>
              </h1>
              <p className="text-lg md:text-lg text-gray-400 mb-8 max-w-xl">
                Brifify uses AI to generate comprehensive project briefs, saving
                you hours of planning and documentation, and endless
                back-and-forth with developers.
              </p>
              <div className="flex flex-col items-center gap-2">
                <button
                  onClick={() => scrollToSection(tryItRef)}
                  className="w-full px-8 py-3 rounded-lg font-medium text-white bg-gradient-to-r from-[#ff3366] to-[#7209b7] hover:opacity-90 transition-all shadow-lg hover:shadow-xl cursor-pointer"
                >
                  Create for free
                </button>
                <span className="text-gray-400 font-medium flex items-center justify-center gap-1">
                  No account creation needed
                </span>
              </div>
            </div>
            <div className="relative rounded-xl overflow-hidden shadow-2xl">
              <div className="absolute inset-0 bg-gradient-to-r from-[#ff3366]/10 to-[#7209b7]/10 rounded-xl"></div>
              <img
                src="/src/assets/placeholder.svg?height=500&width=600"
                alt="Brifify Dashboard Preview"
                className="w-full h-auto rounded-xl"
              />
            </div>
          </div>

          <div className="text-center mb-12">
            <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
              Why Use Brifify?
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto">
              Brifify simplifies the process of creating comprehensive project
              briefs with no technical knowledge or understanding.
            </p>
          </div>
          {/* Why brifify */}
          <div className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <Zap className="w-6 h-6 text-[#4361ee]" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                Save Hours of Back and Forth
              </h3>
              <p className="text-gray-500 text-sm text-left">
                Brifify cuts through the noise by asking the right questions
                upfront. Instead of endless meetings or confusing email threads,
                you get a developer-ready brief fast.
              </p>
            </div>
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <FileText className="w-6 h-6 text-[#7209b7]" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                No Technical Knowledge Required
              </h3>
              <p className="text-gray-500 text-sm text-left">
                You don't need to speak "developer." Brifify guides you
                step-by-step, asking tailored, non-technical questions to
                understand your idea.
              </p>
            </div>
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <Rocket className="w-6 h-6 text-indigo-600" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                Start Your Projects Faster
              </h3>
              <p className="text-gray-500 text-sm text-left">
                Well-scoped projects start smoother and finish faster. Brifify
                helps you align with developers from day one avoiding delays and
                miscommunication.
              </p>
            </div>
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <Brain className="w-6 h-6 text-indigo-600" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                AI-Powered Precision
              </h3>
              <p className="text-gray-500 text-sm text-left">
                Brifify's smart AI assistant asks follow-up questions based on
                your responses. You get a clear, complete brief that covers
                everything a developer would ask.
              </p>
            </div>
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <Share2 className="w-6 h-6 text-indigo-600" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                Flexible Export & Sharing
              </h3>
              <p className="text-gray-500 text-sm text-left">
                Once your brief is ready, export it as a PDF, DOCX or share it
                via a link. You can also edit and customize the brief to fit
                your needs.
              </p>
            </div>
            <div className="p-6 rounded-lg bg-white shadow-md">
              <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4 mx-auto">
                <UserCircle className="w-6 h-6 text-indigo-600" />
              </div>
              <h3 className="text-lg font-semibold mb-2 font-poppins">
                Built for Non-Tech Creators
              </h3>
              <p className="text-gray-500 text-sm text-left">
                Whether you're an entrepreneur, designer, or marketer, Brifify
                helps you define and communicate your project, no tech knowledge
                needed.
              </p>
            </div>
          </div>
        </section>
      </div>

      {/* How It Works Section - Gradient background */}
      <div className="max-w-6xl mx-auto px-4 md:px-8">
        <section ref={howItWorksRef} className="py-16">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
                How It Works
              </h2>
              <p className="text-lg text-gray-400 max-w-2xl mx-auto">
                Brifify uses an interactive, contextual wizard that asks the
                right follow-up questions based on your responses
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
              <div className="relative">
                <div className="absolute top-0 left-0 w-12 h-12 rounded-full bg-[#4361ee] text-white flex items-center justify-center font-bold text-xl">
                  1
                </div>
                <div className="pt-16 pb-8 px-6 bg-white rounded-lg shadow-md h-full">
                  <h3 className="text-lg font-semibold mb-3 font-poppins text-gray-700">
                    Describe Your Idea
                  </h3>
                  <p className="text-gray-500">
                    Start by telling Brifify what you're building in plain
                    English. No technical terms needed.
                  </p>
                </div>
              </div>

              <div className="relative">
                <div className="absolute top-0 left-0 w-12 h-12 rounded-full bg-[#4361ee] text-white flex items-center justify-center font-bold text-xl">
                  2
                </div>
                <div className="pt-16 pb-8 px-6 bg-white rounded-lg shadow-md h-full">
                  <h3 className="text-lg font-semibold mb-3 font-poppins text-gray-700">
                    Answer Smart Questions
                  </h3>
                  <p className="text-gray-500">
                    Brifify asks tailored follow-up questions to uncover key
                    details, based on your answers and context.
                  </p>
                </div>
              </div>

              <div className="relative">
                <div className="absolute top-0 left-0 w-12 h-12 rounded-full bg-[#4361ee] text-white flex items-center justify-center font-bold text-xl">
                  3
                </div>
                <div className="pt-16 pb-8 px-6 bg-white rounded-lg shadow-md h-full">
                  <h3 className="text-lg font-semibold mb-3 font-poppins text-gray-700">
                    Get Your Brief
                  </h3>
                  <p className="text-gray-500">
                    Receive a complete, structured project brief you can share
                    or download, ready for developers to start building.
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-16 max-w-5xl mx-auto bg-white rounded-xl overflow-hidden shadow-lg">
              <div className="p-6 md:p-10">
                <h3 className="text-xl font-semibold mb-4 font-poppins text-gray-700">
                  What's Included in Your Brief
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-4">
                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      A clear summary of what the project is and what it’s meant
                      to do.
                    </p>
                  </div>
                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      A list of key features tailored to your idea.
                    </p>
                  </div>
                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      Suggested platforms like web, iOS, or Android based on
                      your goals.
                    </p>
                  </div>

                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      Recommended tech stack developers can use to build it.
                    </p>
                  </div>
                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      Defined user roles and what each type of user can access
                      or do.
                    </p>
                  </div>
                  <div className="flex items-start">
                    <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                    <p className="text-gray-500 text-left">
                      Additional notes or action items to move your project
                      forward.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Try It Section - White background that extends full width */}
      {/* <div className="w-full bg-white">
        <section ref={tryItRef} className="py-16 px-4 md:px-8 max-w-6xl mx-auto">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
                Try Brifify Now
              </h2>
              <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                Experience how easy it is to create a comprehensive project
                brief
              </p>
            </div>

            <div className="bg-white p-6 md:p-10 rounded-xl shadow-lg max-w-4xl mx-auto border border-gray-100">
              <div className="mb-6">
                <label className="block text-gray-700 font-medium mb-2">
                  Project Name
                </label>
                <input
                  type="text"
                  placeholder="E.g., Website Redesign for XYZ Company"
                  className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-[#4361ee]"
                />
              </div>

              <div className="mb-6">
                <label className="block text-gray-700 font-medium mb-2">
                  Project Type
                </label>
                <select className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-[#4361ee]">
                  <option>Website Development</option>
                  <option>Marketing Campaign</option>
                  <option>Product Launch</option>
                  <option>Branding Project</option>
                  <option>Content Creation</option>
                </select>
              </div>

              <div className="mb-8">
                <label className="block text-gray-700 font-medium mb-2">
                  Brief Description
                </label>
                <textarea
                  placeholder="Briefly describe what you want to achieve with this project..."
                  className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-[#4361ee] min-h-[120px]"
                ></textarea>
              </div>

              <button className="w-full py-3 rounded-lg font-medium text-white bg-gradient-to-r from-[#ff3366] to-[#7209b7] hover:opacity-90 transition-all flex items-center justify-center">
                Generate Brief <ArrowRight className="ml-2 w-5 h-5" />
              </button>
            </div>
          </div>
        </section>
      </div> */}

      {/* Use Cases Section - White background that extends full width */}
      <div className="w-full bg-white">
        <section
          ref={useCasesRef}
          className="py-16 px-4 md:px-8 max-w-6xl mx-auto"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
                Use Cases
              </h2>
              <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                Brifify helps professionals across various industries create
                better project briefs
              </p>
            </div>

            <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div className="flex items-start mb-4">
                  <div className="bg-blue-100 p-3 rounded-lg mr-4">
                    <Sparkles className="w-6 h-6 text-[#4361ee]" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2 font-poppins text-gray-700">
                      Marketing Teams
                    </h3>
                    <p className="text-gray-500">
                      Create comprehensive briefs for campaigns, content
                      strategies, and brand initiatives.
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div className="flex items-start mb-4">
                  <div className="bg-purple-100 p-3 rounded-lg mr-4">
                    <FileText className="w-6 h-6 text-[#7209b7]" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2 font-poppins text-gray-700">
                      Product Managers
                    </h3>
                    <p className="text-gray-500">
                      Document product requirements and specifications with all
                      necessary details.
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div className="flex items-start mb-4">
                  <div className="bg-indigo-100 p-3 rounded-lg mr-4">
                    <Users className="w-6 h-6 text-indigo-600" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2 font-poppins text-gray-700">
                      Agency Teams
                    </h3>
                    <p className="text-gray-500">
                      Streamline client onboarding and project scoping with
                      comprehensive briefs.
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div className="flex items-start mb-4">
                  <div className="bg-green-100 p-3 rounded-lg mr-4">
                    <Zap className="w-6 h-6 text-green-600" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2 font-poppins text-gray-700">
                      Freelancers
                    </h3>
                    <p className="text-gray-500">
                      Create professional project briefs to align with clients
                      and set clear expectations.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Pricing Section - Gradient background */}
      <div className="max-w-6xl mx-auto px-4 md:px-8">
        <section ref={pricingRef} className="py-16">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
                Simple, Transparent Pricing
              </h2>
              <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                Choose the plan that works best for you and your team
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
              {pricingPlans.map((plan, index) => (
                <div
                  key={index}
                  className={`rounded-xl overflow-hidden shadow-lg ${
                    plan.popular ? "ring-2 ring-[#4361ee] relative" : ""
                  }`}
                >
                  {plan.popular && (
                    <div className="absolute top-0 right-0 bg-[#4361ee] text-white px-4 py-1 text-sm font-medium rounded-bl-lg">
                      Most Popular
                    </div>
                  )}
                  <div className="bg-white p-8">
                    <h3 className="text-xl font-semibold mb-2 font-poppins text-gray-700">
                      {plan.name}
                    </h3>
                    <div className="flex items-end mb-4">
                      <span className="text-3xl font-bold text-gray-700">
                        {plan.price}
                      </span>
                      <span className="text-gray-500 ml-1">/{plan.period}</span>
                    </div>
                    <p className="text-gray-500 mb-6">{plan.description}</p>
                    <ul className="space-y-3 mb-8">
                      {plan.features.map((feature, i) => (
                        <li key={i} className="flex items-start">
                          <Check className="w-5 h-5 text-[#4361ee] mt-1 mr-3 flex-shrink-0" />
                          <p className="text-gray-500">{feature}</p>
                        </li>
                      ))}
                    </ul>
                    <button
                      className={`w-full py-3 rounded-lg font-medium transition-all ${
                        plan.popular
                          ? "bg-gradient-to-r from-[#ff3366] to-[#7209b7] text-white hover:opacity-90"
                          : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
                      }`}
                    >
                      {plan.cta}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>

      {/* FAQ Section - White background that extends full width */}
      <div className="w-full bg-white">
        <section ref={faqRef} className="py-16 px-4 md:px-8 max-w-6xl mx-auto">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-4 text-gray-700">
                Frequently Asked Questions
              </h2>
              <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                Find answers to common questions about Brifify
              </p>
            </div>

            <div className="max-w-3xl mx-auto">
              {faqItems.map((item, index) => (
                <div
                  key={index}
                  className="mb-4 bg-white rounded-lg shadow-md overflow-hidden border border-gray-100"
                >
                  <button
                    className="w-full px-6 py-4 text-left flex justify-between items-center focus:outline-none"
                    onClick={() => toggleFaq(index)}
                  >
                    <span className="font-medium text-base font-poppins text-gray-800">
                      {item.question}
                    </span>
                    {openFaq === index ? (
                      <ChevronUp className="w-5 h-5 text-gray-500" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-gray-500" />
                    )}
                  </button>
                  {openFaq === index && (
                    <div className="px-6 pb-4">
                      <p className="text-gray-500">{item.answer}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="mt-16 text-center">
              <p className="text-gray-500 mb-4">Still have questions?</p>
              <button className="px-8 py-3 rounded-lg font-medium text-white bg-[#4361ee] hover:bg-[#3a56d4] transition-all">
                Contact Support
              </button>
            </div>
          </div>
        </section>
      </div>

      {/* CTA Section - Gradient background that extends full width */}
      <div className="w-full bg-gradient-to-r from-[#ff3366] to-[#7209b7]">
        <section className="py-16 md:px-8 max-w-6xl mx-auto text-white">
          <div className="max-w-5xl mx-auto text-center">
            <h2 className="text-2xl md:text-3xl font-bold font-poppins mb-6">
              Ready to Transform Your Project Planning?
            </h2>
            <p className="text-lg opacity-90 mb-8 max-w-2xl mx-auto">
              Join thousands of professionals who are saving time and creating
              better project briefs with Brifify.
            </p>
            <button className="px-8 py-3 rounded-lg font-medium bg-white text-[#4361ee] hover:bg-gray-100 transition-all shadow-lg">
              Get Started for Free
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
